name: Modules CI
on: 
  workflow_call:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  validate:
    uses: rossifumax/terraform-modules-ci/.github/workflows/validate.yaml@ci-test

  lint:
    uses: rossifumax/terraform-modules-ci/.github/workflows/lint.yaml@ci-test

  documentation:
    needs: [lint, validate]
    uses: rossifumax/terraform-modules-ci/.github/workflows/documentation.yaml@ci-test

  code-analysis:
    needs: [documentation]
    uses: rossifumax/terraform-modules-ci/.github/workflows/code-analysis.yaml@ci-test

  examples:
    needs: [code-analysis]
    uses: rossifumax/terraform-modules-ci/.github/workflows/examples.yaml@ci-test