name: TF examples check
on:
  workflow_call:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Checkout CI repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: "claranet/terraform-modules-ci"
          ref: "main"
          path: ".github/terraform-modules-ci"

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93 # v6.2.2
        with:
          tflint_version: v0.52.0
          cache: true

      - name: Prepare TFLint config file
        run: |
          apk update && apk add git jq curl
          export TFLINT_AZURERM_PLUGIN_VERSION=$(curl -s --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' --header 'content-type: application/json' "https://api.github.com/repos/terraform-linters/tflint-ruleset-azurerm/tags" | jq -r '.[0].name' | sed 's/v//')
          sed -i "s/TFLINT_AZURERM_PLUGIN_VERSION/$TFLINT_AZURERM_PLUGIN_VERSION/g" $GITHUB_WORKSPACE/.github/terraform-modules-ci/tflint.hcl

      - name: Install OpenTofu
        run: |
          curl -fsSL https://get.opentofu.org/install-opentofu.sh | sh -s -- --install-method deb
          tofu --version

      - name: Prepare repo
        shell: bash
        run: |
          # Retrieve name of the module
          module_name=$(echo $GITHUB_REPOSITORY | sed 's|claranet/terraform-azurerm-||')
          echo $module_name

          for dir in examples/*; do [ -d "$dir" ] && cp terraform.tfvars.ci "$dir/" || exit $?; done

          sed -i "/ version =.*/d" examples/**/modules.tf examples/**/base.tf

          for dir in examples/*
          do
            # Add latest versions for each example
            modules=$(grep -E "^\s*source(\s+)=" "${dir}/modules.tf" "${dir}/base.tf" | sed 's/^.*= //' | sed 's/--//' | sed 's/"//g' | awk '{for (i=1;i<=NF;i++) if (!a[$i]++) printf("%s%s",$i,FS)}{printf("\n")}')
            for i in $modules
            do
              # If it's a submodule of the current module
              if [[ -z "${i##*"${module_name}"/azurerm//modules*}" ]]; then
                submodule=$(echo ${i} | sed 's/.*modules\///g')
                sed -i 's#\"'"${i}"'\"#\"../../modules/'"${submodule}"'\"#' "${dir}/modules.tf" "${dir}/base.tf"
              # If it's the current module
              elif [[ -z "${i##claranet/"${module_name}"/az*}" ]]; then
                sed -i 's#\"'"${i}"'\"#\"../../\"#' "${dir}/modules.tf" "${dir}/base.tf"
              # If it's the current module with Gitlab URL
              elif [[ -z "${i##*"${module_name}".git*}" ]]; then
                sed -i 's#\"'"${i}"'\"#\"../../\"#g' "${dir}/modules.tf" "${dir}/base.tf"
              # If it's the current module with Github URL
              elif [[ -z "${i##*github.com/claranet/terraform-az*-"${module_name}"*}" ]]; then
                sed -i 's#\"'"${i}"'\"#\"../../\"#' "${dir}/modules.tf" "${dir}/base.tf"
              # If it's a module with Gitlab URL
              elif [[ -z "${i##*ssh://git@git.fr.clara.net*}" ]]; then
                echo "Do nothing with this URL dude !"
              elif [[ -z "${i##*github.com*}" ]]; then
                echo "Do nothing with this URL dude !"
              # If it's a module of Terraform Registry
              else
                sed -i 's#\"'"${i}"'\"#&\n\  version = '"\"> 1.0\""'#' "${dir}/modules.tf" "${dir}/base.tf"
              fi
            done
          done
          cat examples/**/modules.tf

      - name: Init TFLint
        run: tflint --init --config $GITHUB_WORKSPACE/.github/terraform-modules-ci/tflint.hcl
        env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check examples
        shell: bash
        run: |
          for d in $(find . -maxdepth 2 -path './examples/*' -type d -print); do cd $d && echo "current dir $PWD" && tofu init && tofu validate && TFLINT_LOG=info tflint --config $GITHUB_WORKSPACE/.github/terraform-modules-ci/tflint.hcl || exit 1;cd -; done
