name: TF Lint
on:
  workflow_call:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/opentofu/opentofu:1.11.5
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2 # v6.0.2

      - name: Checkout CI repository
        uses: actions/checkout@de0fac2 # v6.0.2
        with:
          repository: "claranet/terraform-modules-ci"
          ref: "main"
          path: ".github/terraform-modules-ci"

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@b480b8f # v6.2.2
        with:
          tflint_version: v0.52.0
          cache: true

      - name: Prepare TFLint config file
        run: |
          apk update && apk add git jq curl
          export TFLINT_AZURERM_PLUGIN_VERSION=$(curl -s --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' --header 'content-type: application/json' "https://api.github.com/repos/terraform-linters/tflint-ruleset-azurerm/tags" | jq -r '.[0].name' | sed 's/v//')
          sed -i "s/TFLINT_AZURERM_PLUGIN_VERSION/$TFLINT_AZURERM_PLUGIN_VERSION/g" $GITHUB_WORKSPACE/.github/terraform-modules-ci/tflint.hcl

      - name: Prepare CI files
        run: |
          if grep -q "hashicorp/azurerm" versions.tf; then
            cat <<EOF > main.tf
              provider "azurerm" {
                features {}
              }
          EOF
          fi

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init --config $GITHUB_WORKSPACE/.github/terraform-modules-ci/tflint.hcl
        env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: TFLint
        run: |
          for d in . $(find . -maxdepth 2 -path './modules/*' -type d -print); do cd $d && echo "current dir $PWD" && tofu init && TFLINT_LOG=debug tflint --config $GITHUB_WORKSPACE/.github/terraform-modules-ci/tflint.hcl || exit $?; cd -; done
