name: TF format and validate
on:
  workflow_call:
jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: fmt
        run: |
          terraform fmt -write=false -diff -check -recursive

      - name: validate
        run: |
          terraform init
          terraform validate
