name: TF format and validate
on:
  workflow_call:
jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/opentofu/opentofu:1.8.4
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: fmt
        run: |
          tofu fmt -write=false -diff -check -recursive

      - name: validate
        run: |
          tofu init
          tofu validate
