name: TF format and validate
on:
  workflow_call:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install OpenTofu and dependencies
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          version: v2026.3.17 # [default: latest] mise version to install
          install: true # [default: true] run `mise install`
          cache: true # [default: true] cache mise using GitHub's cache
          experimental: false # [default: false] enable experimental features

      - name: fmt
        run: |
          mise doctor
          which tofu
          tofu fmt -write=false -diff -check -recursive

      - name: validate
        run: |
          tofu init
          tofu validate
